### ISSUE TITLE
Add fingerprints to rendered templates

### ISSUE THREAD

**Issue by josevalim** [josevalim/live_eex#3]
In order to support rendering of templates nested in other templates, such as:

```elixir
Inner template: <%= render "foo.html" %>
```

We need to change LiveView to cope with nesting. But not only that, we need to fingerprint templates. Imagine this code:

```elixir
Dynamic inner template: <%= if some_condition?, do: render("foo.html"), else: render("bar.html") %>
```

Because each template is different, we need to fingerprint them so we know if we are working with foo or bar whenever we are diffing their data on the client.

**Comment by josevalim** [comment]
Fingerprinting is just the MD5 of the static parts so if we dynamically render something we know if the static parts have to be re-rendered.

Nested live views is a separate discussion that probably does not concern the template engine.

**Comment by tmbb** [comment]
> Fingerprinting is just the MD5 of the static parts so if we dynamically render something we know if the static parts have to be re-rendered.

I don't understand what you're calling "static", then. I think static parts should never be re-rendered. That's the point of geing static.

**Comment by josevalim** [comment]
We want to allow nesting. So you can do this:

```
Dynamic inner template: <%= if some_condition?, do: render("foo.html"), else: render("bar.html") %>
```

and we will be able to consider the static/dynamic parts of a child template. But we need to know if we have foo or bar. Hence the fingerprinting.

**Comment by josevalim** [comment]
In master. I will write docs soon that will explain this in details.

**Comment by josevalim** [comment]
There is a section on fingerprinting here: https://github.com/josevalim/live_eex/blob/3b4a8b727d577d8885f8816ef9adb3d244cb6acf/lib/engine.ex#L153
